/**********************************************************************

This is the loader of MBK pseudo-potential potential generated by ADPACK

MBK pseudo-potential is proposed by 
I. Morrison, D.M. Bylander, and L. Kleinman, Phys. Rev. B 47, 6728 (1993).
and it is a norm-conserving model modified from the Vanderbilt's ultrasoft pseudopotential:
D. Vanderbilt, Phys. Rev. B 41, 7892 (1990).


**********************************************************************/

#pragma once
#include <cstring>
#include <string>
#include <cmath>
#include <vector>
#include "JobParam.h"
#include "RadialGrid2.h"
#include "pp_struct.h"

inline
PseudoPot_MBK* LoadQPS(const char* filepath) {
	JobParam job_param(filepath, "*.Begin", "*.End");
	
	//if (!job_param.IsEqualString("vps.type", "MBK")){
	//	printf("ERROR: VPS of MBK is only supported.");
	//	return nullptr; //error//
	//}

    //const char* BLOCK_KEY = "eq.type";
    //const bool is_independent_j = false;
    //const bool is_independent_j = (job_param.IsEqualString(BLOCK_KEY, "sch") || job_param.IsEqualString(BLOCK_KEY, "sdirac"));


	PseudoPot_MBK* p_pseudo_pot = new PseudoPot_MBK;
	PseudoPot_MBK& pp = *p_pseudo_pot;

    pp.num_radial_projectors = job_param.GetInt("Num.Projectors");
    pp.valence_electron = (int)job_param.GetInt("Num.ValenceElectrons");
    pp.cutoff_vlocal = job_param.GetDouble("Vlocal.Cutoff");

    //cutoff length
    {
		//double max_cutoff = 0.0;
		//int max_l = 0;
		const char* BLOCK_KEY = "ProjectorInfo";
		const int num = job_param.GetBlockNumLines(BLOCK_KEY);
        pp.projector_quantum_l = new int[num];
		for (int i = 0; i < num; ++i) {
			std::string line(job_param.GetBlockString(BLOCK_KEY,i));
			const char* pbegin = line.c_str();
			char* pend = nullptr;
			const int quantum_n = strtol(pbegin, &pend, 10);
			pbegin = pend;
			const int quantum_l = strtol(pbegin, &pend, 10);
			pbegin = pend;
			const double cutoff = strtod(pbegin, &pend);

            pp.projector_quantum_l[i] = quantum_l;

			if (quantum_l < 4) {
				if (pp.cutoff_r[quantum_l] < cutoff) {
					pp.cutoff_r[quantum_l] = cutoff;
					//if (max_cutoff < cutoff) max_cutoff = cutoff;
					//if (max_l < quantum_l) max_l = quantum_l;
				}
			}
		}	


	}
	
	{
		const char* BLOCK_KEY = "ProjectorMatrix";
		const int num = job_param.GetBlockNumLines(BLOCK_KEY);
		//pp.num_radial_projectors = num;
		//pp.projector_quantum_l = new int[num];        
        pp.projector_energy_up = new double[num * 2];
        pp.projector_energy_down = pp.projector_energy_up + num;
        for (int i = 0; i < num; ++i) {
            std::string line(job_param.GetBlockString(BLOCK_KEY, i));
            const char* pbegin = line.c_str();
            char* pend = nullptr;
            const double E_up = strtod(pbegin, &pend);
            
            pp.projector_energy_up[i] = E_up;
            pp.projector_energy_down[i] = E_up;
        }
        
	}




	{
		const char* BLOCK_KEY = "ProjectorVector";
		const int num_grids = job_param.GetBlockNumLines(BLOCK_KEY);
		pp.num_radial_grids = num_grids;
        pp.buffer_size = num_grids * (pp.num_radial_projectors * 2 + 5);
		pp.buffer_all = new double[pp.buffer_size];//+5 means, radius, v_local, pcc_charge, nucl_charge, ve_density//
		pp.radius = pp.buffer_all;
		pp.V_local = pp.buffer_all + num_grids;
		for (int i = 0; i < pp.num_radial_projectors * 2; ++i){
			pp.projector.push_back(pp.buffer_all + (2+i)* num_grids);
		}

		double xi_min;
		double xi;
        for (int i = 0; i < num_grids; ++i) {
            std::string line(job_param.GetBlockString(BLOCK_KEY, i));
            const char* pbegin = line.c_str();
            char* pend = nullptr;
            xi = strtod(pbegin, &pend);
            if (i == 0)xi_min = xi;
            pbegin = pend;
            pp.radius[i] = strtod(pbegin, &pend);
            pbegin = pend;
            pp.V_local[i] = strtod(pbegin, &pend);
            pbegin = pend;
            for (int k = 0; k < pp.num_radial_projectors; ++k) {
                pp.projector[k*2][i] = strtod(pbegin, &pend);
                pp.projector[k * 2 + 1][i] = pp.projector[k * 2][i];
                pbegin = pend;
            }
        }
        
		pp.xi_min = xi_min;
		pp.xi_delta = (xi - xi_min) / (double)(num_grids - 1);

	}


	{
        
        const char* BLOCK_KEY = "PCC";
        const int num_grids = job_param.GetBlockNumLines(BLOCK_KEY);
		if (num_grids > 0) {
			if (pp.num_radial_grids != num_grids) {
				printf("ERROR: %s has incorrect grid size.", BLOCK_KEY);
			}
            
            pp.pcc_charge = pp.buffer_all + (2 + (pp.num_radial_projectors * 2)) * num_grids;
            pp.has_pcc_charge = 1;
			
			double sum_rho=0.0;
			double prev_pcc = 0.0;
			double prev_r = 0.0;
			for (int i = 0; i < num_grids; ++i) {
				std::string line(job_param.GetBlockString(BLOCK_KEY, i));
				const char* pbegin = line.c_str();
				char* pend = nullptr;
				const double r = strtod(pbegin, &pend);
				pbegin = pend;
				const double pcc_c = strtod(pbegin, &pend);				
				pbegin = pend;
				pp.pcc_charge[i] = pcc_c;
				//printf("%d, %.12f, %.12f\n", i, r, pcc_c);

#if 1
				sum_rho += pcc_c*r*r*r;
#elif 1
				sum_rho += prev_pcc * prev_r * prev_r * (r - prev_r);
				prev_pcc = pcc_c;
				prev_r = r;
#else
				if (i < num_grids - 1) {
					sum_rho += pcc_c * pp.radius[i] * pp.radius[i] * (pp.radius[i + 1] - pp.radius[i]);
				}
#endif
			}
			const double xi_delta = pp.xi_delta;
			sum_rho *= xi_delta;
			sum_rho *= 4.0 * M_PI;
			//sum_rho *= 4.0 * std::acos(-1.0);

			printf("PCC charge in Pseudo Potential = %f\n", sum_rho);
		}
	}
	

    {

        const char* BLOCK_KEY = "NuclearCharge";
        const int num_grids = job_param.GetBlockNumLines(BLOCK_KEY);
        if (num_grids > 0) {
            if (pp.num_radial_grids != num_grids) {
                printf("ERROR: %s has incorrect grid size.", BLOCK_KEY);
            }

            pp.nucl_charge = pp.buffer_all + (3 + (pp.num_radial_projectors * 2)) * num_grids;
            pp.has_nucl_charge = 1;

            double sum_rho = 0.0;
            double prev_pcc = 0.0;
            double prev_r = 0.0;
            for (int i = 0; i < num_grids; ++i) {
                std::string line(job_param.GetBlockString(BLOCK_KEY, i));
                const char* pbegin = line.c_str();
                char* pend = nullptr;
                const double r = strtod(pbegin, &pend);
                pbegin = pend;
                const double nucl_c = strtod(pbegin, &pend);
                pbegin = pend;
                pp.nucl_charge[i] = nucl_c;
                //printf("%d, %.12f, %.12f\n", i, r, pcc_c);

#if 1
                sum_rho += nucl_c * r * r * r;
#elif 1
                sum_rho += prev_pcc * prev_r * prev_r * (r - prev_r);
                prev_pcc = pcc_c;
                prev_r = r;
#else
                if (i < num_grids - 1) {
                    sum_rho += pcc_c * pp.radius[i] * pp.radius[i] * (pp.radius[i + 1] - pp.radius[i]);
                }
#endif
            }
            const double xi_delta = pp.xi_delta;
            sum_rho *= xi_delta;
            sum_rho *= 4.0 * M_PI;
            //sum_rho *= 4.0 * std::acos(-1.0);

            printf("Nuclear charge in Pseudo Potential = %f\n", sum_rho);
        }
    }


    {

        const char* BLOCK_KEY = "PseudoValenceDensity";
        const int num_grids = job_param.GetBlockNumLines(BLOCK_KEY);
        if (num_grids > 0) {
            if (pp.num_radial_grids != num_grids) {
                printf("ERROR: %s has incorrect grid size.", BLOCK_KEY);
            }

            pp.ve_density = pp.buffer_all + (4 + (pp.num_radial_projectors * 2)) * num_grids;
            pp.has_ve_density = 1;

            double sum_rho = 0.0;
            double prev_pcc = 0.0;
            double prev_r = 0.0;
            for (int i = 0; i < num_grids; ++i) {
                std::string line(job_param.GetBlockString(BLOCK_KEY, i));
                const char* pbegin = line.c_str();
                char* pend = nullptr;
                const double r = strtod(pbegin, &pend);
                pbegin = pend;
                const double nucl_c = strtod(pbegin, &pend);
                pbegin = pend;
                pp.ve_density[i] = nucl_c;
                //printf("%d, %.12f, %.12f\n", i, r, pcc_c);

                sum_rho += nucl_c * r * r * r;
                
            }
            const double xi_delta = pp.xi_delta;
            sum_rho *= xi_delta;
            sum_rho *= 4.0 * M_PI;

            printf("Pseudo valence charge in Pseudo Potential = %f\n", sum_rho);
        }
    }
	
	
	pp.SortByL();

    pp.cutoff_pcc = pp.cutoff_vlocal;
	return p_pseudo_pot;
			
	
}


inline
int LoadValenceElectronQPS(const char* filepath) {
    JobParam job_param(filepath, "*.Begin", "*.End");
    return job_param.GetInt("Num.ValenceElectrons", 0);
}
