/**********************************************************************

This is the loader of MBK pseudo-potential potential generated by ADPACK

MBK pseudo-potential is proposed by 
I. Morrison, D.M. Bylander, and L. Kleinman, Phys. Rev. B 47, 6728 (1993).
and it is a norm-conserving model modified from the Vanderbilt's ultrasoft pseudopotential:
D. Vanderbilt, Phys. Rev. B 41, 7892 (1990).


**********************************************************************/

#pragma once
#include <cstring>
#include <string>
#include <cmath>
#include <vector>
#include "JobParam.h"
#include "RadialGrid2.h"
#include "UniformGrid.h"
#include "poisson_radial.h"
#include "pp_struct.h"

#define ONCV_CORRECT_VLOCAL  11
#define ONCV_CORRECT_PCC



class SimpleXMLPerser {
private:
    FILE* m_fp=nullptr;

    struct Tag {
        bool is_text = false;
        std::string name;
        std::vector<Tag*> children;
        std::map<std::string, std::string > property;
    };

    static constexpr int SIZE_ROW = 1024;
    char line[SIZE_ROW];
    //int m_pos = -1;
    Tag top_tags;
public:
    ~SimpleXMLPerser() {
        if (m_fp) Close();

        DeleteChildren(top_tags);
    }



    bool Open(const char* filepath) {
        m_fp = fopen(filepath, "r");
        return (m_fp != nullptr);
    }

    void Close() {
        fclose(m_fp);        
    }

    
    void DeleteChildren(Tag& parent) {
        for (auto&& a : parent.children) {
            DeleteChildren(*a);
            delete a;
        }        
    }

    bool IsAlphabet(char x) {
        if (('a' <= x) && (x <= 'z')) return true;
        if (('A' <= x) && (x <= 'Z')) return true;
        if ('-' == x) return true;
        if ('_' == x) return true;
        return false;
    }
    
    bool IsNumber(char x) {
        if (('0' <= x) && (x <= '9')) return true;
        if ('.' == x) return true;
        return false;
    }

    char* NextNotAlphabetNumber(char* offset) {
        for (char* i = offset; (*i) != '\0'; ++i) {
            if(IsAlphabet(*i)) continue;
            if (IsNumber(*i)) continue;            
            return i;
        }
        return nullptr;
    }


    char* NextMeaning(char* offset) {
        constexpr char DELIMITER[] = " \t\r\n";
        constexpr int LENGTH = 4;
        for (char* i = offset; (*i) != '\0'; ++i) {
            int k;
            for (k = 0; k < LENGTH; ++k) {
                if ((*i) == DELIMITER[k]) break;
            }            
            if (k == LENGTH) return i;
        }
        return nullptr;
    }


    char* NextChar(char* offset, int c) {
        for (char* i = offset; (*i) != '\0'; ++i) {
            if ((*i) == c) return i;
        }
        return nullptr;
    }

    char* NextMeaningHelper(char* offset) {
        char* pos = NextMeaning(offset);
        while (pos ==nullptr ) {
            if (fgets(line, SIZE_ROW, m_fp) == nullptr) {
                break;
            }
            pos = NextMeaning(line);
        }
        return pos;
    }


    char* NextCharHelper(char* offset, int c) {
        char* pos = NextChar(offset, c);
        while (pos == nullptr) {
            if (fgets(line, SIZE_ROW, m_fp) == nullptr) {
                break;
            }
            pos = NextChar(0, c);
        }
        return pos;
    }

    void Perse() {
        if (fgets(line, SIZE_ROW, m_fp) == nullptr) {
            return;
        }
        //top_tags = new Tag;
        LoadChildren(&top_tags, line);
        
    }

    char* LoadChildren(Tag* parent, char* pstart) {
        //内部タグの読み込み//
        char* pos = NextMeaningHelper(pstart);
        char* pend;
        while (pos) {
            if (*pos == '<') {
                if (*(pos + 1) == '/') {
                    pend = NextChar(pos + 2, '>');
                    return pend + 1;
                }else if (*(pos + 1) == '!') {
                    //comment
                    pend = NextCharHelper(pos + 4, '>');
                    while (pend) {
                        if ((*(pend - 1) == '-') && (*(pend - 2) == '-')) {
                            //コメントタグの終端//
                            break;
                        }
                        pend = NextCharHelper(pend + 1, '>');
                    }
                    if (pend == nullptr) {
                        //コメント終端されていない//
                        return nullptr;
                    }
                    pend++;

                } else {
                    Tag* ch_tag;
                    pend = LoadTag(pos, &ch_tag);
                    parent->children.push_back(ch_tag);
                }
            } else {
                //text
                Tag* ch_tag = new Tag;
                ch_tag->is_text = true;
                pend = NextChar(pos, '<');
                while (pend == nullptr) {
                    ch_tag->name += pos;

                    if (fgets(line, SIZE_ROW, m_fp) == nullptr) {
                        break;
                    }
                    pos = line;
                    pend = NextChar(pos, '<');
                }

                parent->children.push_back(ch_tag);
                if (pend == nullptr) {//file終端//
                    return nullptr;
                }

            }
            pos = NextMeaningHelper(pend);
        }
        return nullptr;
    }

    char* LoadTag(char* offset, Tag** ptag) {
                
        char* pos = NextMeaningHelper(offset);
        if (pos == nullptr) return nullptr;

        if (*pos != '<') {
            return nullptr;//error
        }
        //tag start//////////////////////////
        char* pend = NextNotAlphabetNumber(pos+1);
        Tag* tag = new Tag;
        *ptag = tag;
        tag->name = std::string(pos + 1).substr(0, pend - pos-1);
                

        pos = NextMeaningHelper(pend);
        while (pos) {
                
            if (*pos == '/') {
                if (*(pos + 1) == '>') {
                    return pos + 2;//tag終了//
                }
            }else if (*pos == '>') {
                //開始タグだった//
                //内部の読み込み//
                pend = pos + 1;
                break;
            }


            //property list//
            pend = NextNotAlphabetNumber(pos);
            std::string prop_name = std::string(pos).substr(0, pend - pos);

            pos = NextMeaningHelper(pend);
                    
            if (*pos == '=') {
                std::string prop_value;

                //valueがあるので読み込み//
                pos = NextMeaningHelper(pos + 1);
                if (*pos == '\"') {
                    pend = NextCharHelper(pos+1, '\"');
                    prop_value = std::string(pos + 1).substr(0, pend - pos - 1);
                }else{
                    pend = NextNotAlphabetNumber(pos);
                    prop_value = std::string(pos).substr(0, pend - pos);
                }

                tag->property.insert(std::make_pair(prop_name, prop_value));

                pos = NextMeaningHelper(pend + 1);
            } else {

                tag->property.insert(std::make_pair(prop_name, std::string()));

            }
        }

        //内部タグの読み込み//
        pos = LoadChildren(tag, pend);
        return pos;
    }

    //////////////////////////////////
    //検索, 値の取得//////////////////
    //////////////////////////////////
    const std::string GetProperty(const std::vector<std::string>& tag_layer, const std::string& prop_name) {
        Tag* tag = &top_tags;
        for (const auto& t : tag_layer) {
            bool is_found = false;
            for (auto& ch : tag->children) {
                if (ch->name == t) {
                    tag = ch;
                    is_found = true;
                    break;
                }
            }
            if (is_found == false)return std::string();
        }

        auto it = tag->property.find(prop_name);
        if(it == tag->property.end()){
            return std::string();
        }
    
        return it->second;
    }

    const std::string GetText(const std::vector<std::string>& tag_layer) {
        Tag* tag = &top_tags;
        for (const auto& t : tag_layer) {
            bool is_found = false;
            for (auto& ch : tag->children) {
                if (ch->name == t) {
                    tag = ch;
                    is_found = true;
                    break;
                }
            }
            if (is_found == false)return std::string();
        }

        if(tag->children[0]->is_text){
            return tag->children[0]->name;
        }

        return std::string();
    }
};

inline
std::vector<double> ReadDoubleList(const std::string& text, int count) {
    std::vector<double> vals;

    
    const char* p = text.c_str();
    for(int i = 0; i < count; ++i){
        char* endptr;
        double d = std::strtod(p, &endptr);
        /*if (p == endptr) {
            break;
        }
        */
        //数字がもうないときはstrtodが0.0を返すことを利用してvectorを0で埋める//
        vals.push_back(d);
        p = endptr;    
    }
    return vals;
}

//
// -1/2が掛かっている
inline 
void LaplacianOnUniformGrid(const std::vector<double>& uni_v_local, int num_uni_grid, const std::vector<double>& uni_radius, std::vector<double>& uni_nucl_rho) {
    const double dr = uni_radius[1] - uni_radius[0];
    for (int i = 2; i < num_uni_grid - 2; ++i) {
        const double dv_dr = (8.0 * (uni_v_local[i + 1] - uni_v_local[i - 1]) - ((uni_v_local[i + 2] - uni_v_local[i - 2]))) / (12.0 * dr);
        const double d2v_dr2 = (-30.0 * uni_v_local[i] + 16.0 * (uni_v_local[i + 1] + uni_v_local[i - 1]) - ((uni_v_local[i + 2] + uni_v_local[i - 2]))) / (12.0 * dr * dr);

        uni_nucl_rho[i] = -(1.0 / (8.0 * M_PI)) * (d2v_dr2 + (2.0 / uni_radius[i]) * dv_dr);
    }
    uni_nucl_rho[0] = uni_nucl_rho[1] = uni_nucl_rho[2];
    uni_nucl_rho[num_uni_grid - 2] = 0.0;
    uni_nucl_rho[num_uni_grid - 1] = 0.0;

}

//note: unit of energy in UPF is Ry, that is 1/2 Hartree
inline
PseudoPot_MBK* LoadUPF_ONCV(const char* filepath) {

    const double sqrt_half = sqrt(2.0);
    const double isqrt_half = 1.0 / sqrt_half;

    SimpleXMLPerser xml;
    if (!xml.Open(filepath)){
        return nullptr;
    }
    xml.Perse();

    PseudoPot_MBK* p_pseudo_pot = new PseudoPot_MBK;
    PseudoPot_MBK& pp = *p_pseudo_pot;

    auto a = xml.GetProperty({ "UPF" ,"PP_HEADER" }, "number_of_proj");
    pp.num_radial_projectors = std::stol(a);

    a = xml.GetProperty({ "UPF" ,"PP_HEADER" }, "z_valence");
    pp.valence_electron = std::stol(a);

    //a = xml.GetProperty({ "UPF" ,"PP_HEADER" }, "rho_cutoff");
    //pp.cutoff_vlocal = std::stod(a);
    //note: cutoff_vlocal is not writtern on upf for ONCV

    
    a = xml.GetProperty({ "UPF" ,"PP_MESH", "PP_R" }, "size");
    const int num_uni_grid = std::stol(a);
    auto vals = ReadDoubleList(xml.GetText({ "UPF" ,"PP_MESH", "PP_R" }), num_uni_grid);

    UniformGrid uni_grid(num_uni_grid, vals[0], vals[1]- vals[0]);
    
    const double xi_min = -9.0;
    const double xi_max = log(vals[num_uni_grid-1]);
    const int num_grids = 1000;
    const double xi_delta = (xi_max - xi_min) / (double)num_grids;

    pp.xi_min = xi_min;
    pp.xi_delta = xi_delta;

    //cutoff length
    {
		double cutoff_vlocal = 0.0;
        pp.projector_quantum_l = new int[pp.num_radial_projectors];
        
		for (int i = 0; i < pp.num_radial_projectors; ++i) {

            std::string pp_proj_name = "PP_BETA." + std::to_string(i + 1);

            a = xml.GetProperty({ "UPF" ,"PP_NONLOCAL", pp_proj_name }, "angular_momentum");
            const int quantum_l = std::stol(a);

            a = xml.GetProperty({ "UPF" ,"PP_NONLOCAL", pp_proj_name }, "cutoff_radius");
            const double cutoff = std::stod(a);


            pp.projector_quantum_l[i] = quantum_l;

			if (quantum_l < 4) {
				if (pp.cutoff_r[quantum_l] < cutoff) {
					pp.cutoff_r[quantum_l] = cutoff;
					if (cutoff_vlocal < cutoff) cutoff_vlocal = cutoff;
				}
			}
		}	
        pp.cutoff_vlocal = cutoff_vlocal;

	}


	{
		//const char* BLOCK_KEY = "ProjectorMatrix";
        const int num = pp.num_radial_projectors;
		//pp.num_radial_projectors = num;
		//pp.projector_quantum_l = new int[num];        
        pp.projector_energy_up = new double[num * 2];
        pp.projector_energy_down = pp.projector_energy_up + num;

        auto B_ij = ReadDoubleList(xml.GetText({ "UPF" ,"PP_NONLOCAL","PP_DIJ" }), num* num);

        for (int i = 0; i < num; ++i) {

            const double E_up = B_ij[i + num * i] /2.0;//unit of upf is Ry.

            pp.projector_energy_up[i] = E_up;
            pp.projector_energy_down[i] = E_up;
        }
        
	}


    double ve_total = 0.0;
    double nucl_total = 0.0;

	
	//const char* BLOCK_KEY = "ProjectorVector";
	//const int num_grids = job_param.GetBlockNumLines(BLOCK_KEY);
	pp.num_radial_grids = num_grids;
    pp.buffer_size = num_grids * (pp.num_radial_projectors * 2 + 5);
	pp.buffer_all = new double[pp.buffer_size];//+5 means, radius, v_local, pcc_charge, nucl_charge, ve_density//
	pp.radius = pp.buffer_all;
	pp.V_local = pp.buffer_all + num_grids;
	for (int i = 0; i < pp.num_radial_projectors * 2; ++i){
		pp.projector.push_back(pp.buffer_all + (2+i)* num_grids);
	}

    for (int i = 0; i < num_grids; ++i) {
        const double r = exp((double)i * xi_delta + xi_min);
        pp.radius[i] = r;
    }

        
    auto uni_v_local = ReadDoubleList(xml.GetText({ "UPF" ,"PP_LOCAL" }), num_uni_grid);

    for (int i = 0; i < num_grids; ++i) {
        const double r = pp.radius[i];
        pp.V_local[i] = uni_grid.GetValue(r, uni_v_local.data(), UniformGrid::EVEN) / 2.0;//unit of upf is Ry
    }

    std::vector<double> uni_nucl_rho(num_uni_grid);
#if 1
    LaplacianOnUniformGrid(uni_v_local, num_uni_grid, vals, uni_nucl_rho);
#else
    {
        const double dr = vals[1] - vals[0];
        for (int i = 2; i < num_uni_grid-2; ++i) {
            const double dv_dr = (8.0 * (uni_v_local[i + 1] - uni_v_local[i - 1]) - ((uni_v_local[i + 2] - uni_v_local[i - 2]))) / (12.0 * dr);
            const double d2v_dr2 = (-30.0 * uni_v_local[i] + 16.0 * (uni_v_local[i + 1] + uni_v_local[i - 1]) - ((uni_v_local[i + 2] + uni_v_local[i - 2]))) / (12.0 * dr * dr);

            uni_nucl_rho[i] = -(1.0 / (8.0 * M_PI)) * (d2v_dr2 + (2.0/vals[i])* dv_dr);
        }
        uni_nucl_rho[0] = uni_nucl_rho[1] = uni_nucl_rho[2];
        uni_nucl_rho[num_uni_grid - 2] = 0.0;
        uni_nucl_rho[num_uni_grid - 1] = 0.0;
    }
#endif

    for (int k = 0; k < pp.num_radial_projectors; ++k) {

        std::string pp_proj_name = "PP_BETA." + std::to_string(k + 1);
        auto uni_proj = ReadDoubleList(xml.GetText({ "UPF" ,"PP_NONLOCAL", pp_proj_name }), num_uni_grid);
        const int l = pp.projector_quantum_l[k];
        const int even_odd = (l & 0x1) ? UniformGrid::ODD : UniformGrid::EVEN;

        //ONCVの入力値の原点付近がエラーが大きいので対策
        //projはrが掛かっているので、rで割ってから補間する
        for (int i = 1; i < num_uni_grid; ++i) {
            const double r = vals[i];
            uni_proj[i] /= r;
        }
        uni_proj[0] = (l==0)?uni_proj[1] : 0.0;

        for (int i = 0; i < num_grids; ++i) {
            const double r = pp.radius[i];
            double proj = uni_grid.GetValue(r, uni_proj.data(), even_odd);
            pp.projector[k * 2][i] = proj;
            pp.projector[k * 2 + 1][i] = proj;

        }

        //test//
        //std::string pp_chi_name = "PP_CHI." + std::to_string(k + 1);
        //auto uni_chi = ReadDoubleList(xml.GetText({ "UPF" ,"PP_PSWFC", pp_chi_name }), num_uni_grid);

        /*
        * //note: chiは価電子の軌道しかないのでbetaと内積の確認ができない//
        double chi_proj = 0.0;
        for (int i = 0; i < num_uni_grid; ++i) {
            chi_proj += uni_chi[i] * uni_proj[i];
        }
        chi_proj *= (vals[1] - vals[0]) * 4.0 * M_PI;

        printf("chi_proj(%d) = %f\n", k+1, chi_proj);
        */

    }
        
    {
        //note: pcc is not multiplied by 4\pi*r^2, while ve_den is multiplied by 4\pi*r^2//
        pp.pcc_charge = pp.buffer_all + (2 + (pp.num_radial_projectors * 2)) * num_grids;
        std::string lines = xml.GetText({ "UPF" ,"PP_NLCC" });
        if (lines.length() == 0) {
            pp.has_pcc_charge = 0;
        } else {
            pp.has_pcc_charge = 1;

            auto uni_pcc = ReadDoubleList(lines, num_uni_grid);

#ifdef ONCV_CORRECT_PCC
            double sum = 0.0;
            double max_p = 0.0;
            int max_point = 0;
            for (int i = 0; i < num_uni_grid; ++i) {
                const double r2p = uni_pcc[i] * vals[i] * vals[i];
                sum += r2p;
                if (max_p < uni_pcc[i]) {
                    max_p = uni_pcc[i];
                    max_point = i;
                }
            }
            sum *= 4.0 * M_PI * (vals[1] - vals[0]);


            const double PCC_UNDER_lIMIT = 1.0e-6 * max_p;
            int max_valid_i = max_point;
            for (int i = max_point; i < num_uni_grid; ++i) {
                if (uni_pcc[i]< PCC_UNDER_lIMIT) {
                    max_valid_i = i;
                    break;
                }
            }
            
            pp.cutoff_pcc = vals[max_valid_i + 1];
            const int i_cutoff_pcc = (int)((log(pp.cutoff_pcc) - xi_min) / xi_delta);

            for (int i = 0; i < i_cutoff_pcc; ++i) {
                const double r = pp.radius[i];
                double pcc = uni_grid.GetValue(r, uni_pcc.data(), UniformGrid::EVEN);
                pp.pcc_charge[i] = pcc;
            }
            for (int i = i_cutoff_pcc; i < num_grids; ++i) {
                pp.pcc_charge[i] = 0.0;
            }

#else            
            pp.cutoff_pcc = pp.cutoff_vlocal;
            for (int i = 0; i < num_grids; ++i) {
                const double r = pp.radius[i];
                double pcc = uni_grid.GetValue(r, uni_pcc.data(), UniformGrid::EVEN);
                pp.pcc_charge[i] = pcc;
            }
#endif
        }
    }

    {

        pp.nucl_charge = pp.buffer_all + (3 + (pp.num_radial_projectors * 2)) * num_grids;
        pp.has_nucl_charge = 1;

        for (int i = 0; i < num_grids; ++i) {
                
            double r = pp.radius[i];
            //double xi = (double)i * xi_delta + xi_min;
            /*if (i < 5) { //error 回避//
                xi = (double)5 * xi_delta + xi_min;
                r = exp(xi);
            }*/
                
            //pp.nucl_charge[i] =  (1.0/ (2.0*M_PI))* RadialGrid2::GetLaplacian(r, pp.V_local, 0, num_grids, xi_min, xi_delta);
            //pp.nucl_charge[i] = (1.0/ (2.0*M_PI))* RadialGrid2::GetLaplacianByXi(xi, pp.V_local, 0, num_grids, xi_min, xi_delta) / (r*r);
                
            //note: differece to be multiplied by (1/2) is to convert the energy unit of Vlocal from Ry to Hartree .
            //pp.nucl_charge[i] = (1.0 / (4.0 * M_PI)) * uni_grid.GetLaplacian(std::max(r, 1.0e-14), uni_v_local.data(), 0);
            pp.nucl_charge[i] = uni_grid.GetValue(r, uni_nucl_rho.data(), UniformGrid::EVEN);
            nucl_total += pp.nucl_charge[i] * r * r * r;
        }
        nucl_total *= 4.0 * M_PI * xi_delta;
    }

    {

        pp.ve_density = pp.buffer_all + (4 + (pp.num_radial_projectors * 2)) * num_grids;
        pp.has_ve_density = 1;

        auto uni_ve_rho = ReadDoubleList(xml.GetText({ "UPF" ,"PP_RHOATOM" }), num_uni_grid);
        /*
        for (int i = 0; i < num_grids; ++i) {
            ve_total += uni_ve_rho[i];// *vals[i] * vals[i];
        }
        //ve_total *= 4.0 * M_PI * (vals[1] - vals[0]);
        ve_total *= (vals[1] - vals[0]);
        */

        //note: ve_density include 4\pi*r^2
        for (int i = 0; i < num_grids; ++i) {
            const double r = pp.radius[i];
            const double rho_ve_4pir2 = uni_grid.GetValue(r, uni_ve_rho.data(), UniformGrid::EVEN);// *isqrt_half;

            pp.ve_density[i] = rho_ve_4pir2 / (4.0 * M_PI * r * r);
            ve_total += rho_ve_4pir2 * r;
        }
        ve_total *= xi_delta;

    }
	
    //////////////////////////////////////////////////////////
    //Vlocalがカットオフ長の外側でQ/rに一致しない問題の補正//
    /////////////////////////////////////////////////////////
    std::vector<double> V_local_cor(num_grids);
    std::vector<double> nucl_rho_cor(num_grids);
    double cutoff_vlocal_cor = pp.cutoff_vlocal;

#if ONCV_CORRECT_VLOCAL == 3
    {
        std::vector<double> uni_vlocal_cor(num_uni_grid);
        std::vector<double> uni_nucl_rho_cor(num_uni_grid);
        //uniform グリッドでnucl_rhoの修正//
        double dr = vals[1] - vals[0];
        const int i_cutoff = (int)floor(pp.cutoff_vlocal / dr);
        auto f_c = [](double x) {
            return x * x * x * (6.0 * x * x - 15.0 * x + 10.0);
            };

        //問題のタイプを特定
        //0: 問題なし(rhoがカットオフ外で0、カットオフで微分も0)
        //1: 問題あり、核の密度が正のみ
        //2: 問題あり、核の密度が正負の領域を持つ
        
        const double n_c = uni_nucl_rho[i_cutoff];
        const double dn_dr_c = (uni_nucl_rho[i_cutoff + 1] - uni_nucl_rho[i_cutoff - 1]) / (2.0 * dr);
        int problem_type = 0;
        if( (fabs(n_c) < 1.0e-6) && (fabs(dn_dr_c) < 1.0e-6)){
            problem_type = 0;
        } else {
            problem_type = 1;            
        }
        //密度が正負を跨ぐか確認
        int count_node = 0;
        int i_2nd_peak = 0;
        int i_2nd_node = 0;
        for (int i = 1; i < i_cutoff-1; ++i) {
            if (uni_nucl_rho[i] * uni_nucl_rho[i + 1] < 0.0) {
                count_node++;
                if (count_node == 2) {
                    i_2nd_node = i;
                }
            }
            if (count_node == 1) {
                //負電荷のピーク位置//
                if ((uni_nucl_rho[i + 1] - uni_nucl_rho[i]) * (uni_nucl_rho[i] - uni_nucl_rho[i - 1]) < 0.0) {
                    i_2nd_peak = i;
                }
            }
        }
        
        if (count_node >= 2) {
            problem_type = 2;

            //2nd peakと2nd nodeの中間から4次関数に接続してカットオフで0になるようにする//
            const int i_inside = (i_2nd_node + i_2nd_peak) / 2;
            const double w = vals[i_cutoff] - vals[i_inside];
            const double n_in = uni_nucl_rho[i_inside];
            const double dn_dr_in = (uni_nucl_rho[i_inside + 1] - uni_nucl_rho[i_inside - 1]) / (2.0 * dr);
#if 1
            const double w0 = 4.0 * n_in / (-dn_dr_in);
            const double x0 = vals[i_inside] + w0;
            const double a = n_in / (w0 * w0 * w0 * w0);
            auto g = [&](double x) {
                if (x < x0) {
                    double r = -(x - x0);
                    double r2 = r * r;
                    return a * r2 * r2;
                } else {
                    return 0.0;
                }
                };

            if (x0 > vals[i_cutoff]) {
                problem_type = 1;//さらに再調整が必要
            }
#else
            const double a = (-dn_dr_in / 2.0 - n_in / w) / (w * w * w);
            const double b = (+dn_dr_in / 2.0 + 2.0*n_in / w) / (w);
            const double x0 = vals[i_cutoff];
            auto g = [&](double x) {
                double r = -(x - x0);
                double r2 = r * r;
                return a * r2 * r2 + b * r2;
                };
#endif
            for (int i = i_cutoff; i < num_uni_grid; ++i) {
                uni_nucl_rho_cor[i] = 0.0;  //factor 2 means Hartree to Ry
            }
            for (int i = 0; i < i_inside; ++i) {
                uni_nucl_rho_cor[i] = uni_nucl_rho[i];
            }
            for (int i = i_inside; i < i_cutoff; ++i) {
                uni_nucl_rho_cor[i] = g(vals[i]);
            }
        } 
        
        if (problem_type == 1) {
            //カットオフ関数を単にかけて調整//

            for (int i = i_cutoff; i < num_uni_grid; ++i) {
                uni_nucl_rho_cor[i] = 0.0;  //factor 2 means Hartree to Ry
            }
            const int i_inside = (int)floor(pp.cutoff_vlocal * 0.8 / dr);
            for (int i = 0; i < i_inside; ++i) {
                uni_nucl_rho_cor[i] = uni_nucl_rho[i];
            }


            const double width = vals[i_cutoff] - vals[i_inside];
            for (int i = i_inside; i < i_cutoff; ++i) {
                const double x = (vals[i] - vals[i_inside]) / width;
                double f = f_c(x);
                uni_nucl_rho_cor[i] = (1.0 - f) * uni_nucl_rho[i];
            }
        }

        if(problem_type>0){
            //補正したuni_nucl_rhoを対数座標に変換//
            for (int i = 0; i < num_grids; ++i) {
                const double r = pp.radius[i];
                nucl_rho_cor[i] = uni_grid.GetValue(r, uni_nucl_rho_cor.data(), UniformGrid::EVEN);
            }

            //動径座標の1Dポアソンを解いてVlocalとする//
            PoissonRadial(nucl_rho_cor.data(), num_grids, pp.radius, pp.xi_delta, V_local_cor.data());
        }

    }
#elif ONCV_CORRECT_VLOCAL == 2
    {
        std::vector<double> uni_vlocal_cor(num_uni_grid);
        std::vector<double> uni_nucl_rho_cor(num_uni_grid);
        //uniform グリッドでnucl_rhoの修正//
        double dr = vals[1] - vals[0];
        const int i_cutoff = (int)floor(pp.cutoff_vlocal / dr);
        for (int i = i_cutoff; i < num_uni_grid; ++i) {
            uni_nucl_rho_cor[i] = 0.0;  //factor 2 means Hartree to Ry
        }
        const int i_inside = (int)floor(pp.cutoff_vlocal * 0.6 / dr);
        for (int i = 0; i < i_inside; ++i) {
            uni_nucl_rho_cor[i] = uni_nucl_rho[i];
        }

        auto f_c = [](double x) {
            return x * x * x * (6.0 * x * x - 15.0 * x + 10.0);
            };
        const double width = vals[i_cutoff] - vals[i_inside];
        for (int i = i_inside; i < i_cutoff; ++i) {
            const double x = (vals[i] - vals[i_inside]) / width;
            double f = f_c(x);
            uni_nucl_rho_cor[i] = (1.0 - f) * uni_nucl_rho[i];
        }

        //補正したuni_nucl_rhoを対数座標に変換//
        for (int i = 0; i < num_grids; ++i) {
            const double r = pp.radius[i];
            nucl_rho_cor[i] = uni_grid.GetValue(r, uni_nucl_rho_cor.data(), UniformGrid::EVEN);
        }

        //動径座標の1Dポアソンを解いてVlocalとする//
        PoissonRadial(nucl_rho_cor.data(), num_grids, pp.radius, pp.xi_delta, V_local_cor.data());        
                

    }

#elif ONCV_CORRECT_VLOCAL == 11
    {
        std::vector<double> uni_vlocal_cor(num_uni_grid);
        std::vector<double> uni_nucl_rho_cor(num_uni_grid);

        double dr = vals[1] - vals[0];
        int i_cutoff = (int)floor(pp.cutoff_vlocal / dr);

        //7th order
        auto f_c = [](double x) {
            return x * x * x * x * (-20.0 * x * x * x + 70.0 * x * x - 84.0 * x + 35.0);
            };

        //nodeの存在を探す//
        //ここでのnodeは密度がx軸を跨いで符号が入れ替わる点
        //もしくは、符号は入れ変わらないが密度が2こぶラクダのように再度大きくなる時の谷底(水素で確認)
        //方針:
        //ノード数が1
        int count_node = 0;
        int i_1st_node = 0;
        int i_2nd_node = 0;
        int i_last_inside_node = 0;
        int i_r2_peak = 0;
        double r2rho_min = 0.0;
        for (int i = 1; i < num_uni_grid - 1; ++i) {
            if (uni_nucl_rho[i] * uni_nucl_rho[i + 1] < 0.0) {
                count_node++;
                if (count_node == 1) {
                    i_1st_node = i;
                } else if (count_node == 2) {
                    i_2nd_node = i;
                }
                if (i <= i_cutoff) {
                    i_last_inside_node = i;
                }
            }  

            double r2rho = vals[i] * vals[i] * uni_nucl_rho[i];
            if (r2rho_min > r2rho) {
                r2rho_min = r2rho;
                i_r2_peak = i;
            }
        }

        //i_cutoffを広げる必要がある場合
        if(i_2nd_node > i_cutoff){            
            i_cutoff = std::min(i_2nd_node, ((int)(i_cutoff * 1.5)));
            cutoff_vlocal_cor = vals[i_cutoff];
        }
   
#if 1
        //内側の接続点を、r^2*rhoのピークの半分の高さの点にする場合//
        int i_inside = 0;
        for (int i = i_r2_peak+1; i < i_cutoff - 1; ++i) {
            double r2rho = vals[i] * vals[i] * uni_nucl_rho[i];
            if (r2rho_min * 0.5 < r2rho) {
                i_inside = i;
                break;
            }
        }
        //int i_inside = i_r2_half;

#else
        //内側の接続点を、二階微分が0の点にする場合//
        int i_inside;
        if (count_node == 0) {
            i_inside = (int)((double)i_cutoff * 0.7);
        }else if (count_node == 1) {
            i_cutoff = i_last_inside_node;
            i_inside = (int)((double)i_1st_node * 0.7);
        } else {
            //i_cutoff = i_last_inside_node;
            i_inside = (int)((double)i_1st_node * 1.0);
        }

        //inside 接続点の探索//
        {
            const int i0= (int)(0.1 * (double)i_cutoff);
            const double init_d2f_dx = (uni_nucl_rho[i0+1] - 2.0 * uni_nucl_rho[i0] + uni_nucl_rho[i0-1]);
            for (int i = i0+1; i < i_cutoff - 1; ++i) {
                double d2f_dx = (uni_nucl_rho[i+1] - 2.0 * uni_nucl_rho[i] + uni_nucl_rho[i-1]);
                if (d2f_dx * init_d2f_dx < 0.0) {
                    i_inside = i;
                    break;
                }
            }
        }
#endif

        //uniform グリッドでvlocalの修正//
        for (int i = i_cutoff; i < num_uni_grid; ++i) {
            uni_vlocal_cor[i] = -2.0 * pp.valence_electron / vals[i];  //factor 2 means Hartree to Ry
        }
        
        for (int i = 0; i < i_inside; ++i) {
            uni_vlocal_cor[i] = uni_v_local[i];
        }


        const double width = vals[i_cutoff] - vals[i_inside];
        for (int i = i_inside; i < i_cutoff; ++i) {
            const double x = (vals[i] - vals[i_inside]) / width;
            double f = f_c(x);
            uni_vlocal_cor[i] = f * (-2.0 * pp.valence_electron / vals[i]) + (1.0 - f) * uni_v_local[i];
        }

        //補正したvlocalを対数座標に変換//
        for (int i = 0; i < num_grids; ++i) {
            const double r = pp.radius[i];
            V_local_cor[i] = uni_grid.GetValue(r, uni_vlocal_cor.data(), UniformGrid::EVEN) / 2.0;//unit of upf is Ry
        }

        //補正したvlocalに対応するnucl_rhoを算出
        LaplacianOnUniformGrid(uni_vlocal_cor, num_uni_grid, vals, uni_nucl_rho_cor);
        //補正したvlocalを対数座標に変換//
        for (int i = 0; i < num_grids; ++i) {
            const double r = pp.radius[i];
            nucl_rho_cor[i] = uni_grid.GetValue(r, uni_nucl_rho_cor.data(), UniformGrid::EVEN);
        }

    }
#elif ONCV_CORRECT_VLOCAL == 1
    {
        std::vector<double> uni_vlocal_cor(num_uni_grid);
        std::vector<double> uni_nucl_rho_cor(num_uni_grid);
#if 0
        //Fermi (sigmoid)
        auto f_c = [](double x) {
            double a = 2.5;
            return  1.0 / (1.0 + exp(-a * (2.0 * x - 1.0)));
            };
#elif 0
        //gousian
        auto f_c = [](double x) {
            double a = 2.5;
            return  (exp(a * (x * x)) - exp(-a * (x * x))) / (exp(a * (x * x)) + exp(-a * (x*x)));
            };
#elif 1
        //7th order
        auto f_c = [](double x) {
            return x * x * x * x * (-20.0*x*x*x + 70.0 * x * x - 84.0 * x + 35.0);
            };
#else
        //5th order
        auto f_c = [](double x) {
            return x * x * x * (6.0 * x * x - 15.0 * x + 10.0);
            };
#endif

        //uniform グリッドでvlocalの修正//
        double dr = vals[1] - vals[0];
        const int i_cutoff = (int)floor(pp.cutoff_vlocal / dr);
        for (int i = i_cutoff; i < num_uni_grid; ++i) {
            uni_vlocal_cor[i] = -2.0*pp.valence_electron / vals[i] ;  //factor 2 means Hartree to Ry
        }
        const int i_inside = (int)floor(pp.cutoff_vlocal * 0.5 / dr);
        for (int i = 0; i < i_inside; ++i) {
            uni_vlocal_cor[i] = uni_v_local[i];
        }
        
        
        const double width = vals[i_cutoff] - vals[i_inside];
        for (int i = i_inside; i < i_cutoff; ++i) {
            const double x = (vals[i] - vals[i_inside]) / width;
            double f = f_c(x);
            uni_vlocal_cor[i] = f * (-2.0 * pp.valence_electron / vals[i]) + (1.0 - f) * uni_v_local[i];
        }
        
        //補正したvlocalを対数座標に変換//
        for (int i = 0; i < num_grids; ++i) {
            const double r = pp.radius[i];
            V_local_cor[i] = uni_grid.GetValue(r, uni_vlocal_cor.data(), UniformGrid::EVEN)/2.0;//unit of upf is Ry
        }

        //補正したvlocalに対応するnucl_rhoを算出
        LaplacianOnUniformGrid(uni_vlocal_cor, num_uni_grid, vals, uni_nucl_rho_cor);
        //補正したvlocalを対数座標に変換//
        for (int i = 0; i < num_grids; ++i) {
            const double r = pp.radius[i];
            nucl_rho_cor[i] = uni_grid.GetValue(r, uni_nucl_rho_cor.data(), UniformGrid::EVEN);
        }

    }
#endif


#ifdef _DEBUG
    {
        int rank;
        MPI_Comm_rank(MPI_COMM_WORLD, &rank);
        if (rank == 0) {
            FILE* fp = fopen("test_upf_out1.txt","w");
            fprintf(fp,"#r, vlocal, rho_nucl, pcc, int_rho_nucl, vlocal(cor), rho_nucl(col), int_rho_nucl(col), beta(1), beta(2), ...\n");
            double nucl_total = 0.0;
            double nucl_total_cor = 0.0;
            for (int i = 0; i < num_grids; ++i) {
                double r = pp.radius[i];
                nucl_total += pp.nucl_charge[i] * r * r * r * 4.0*M_PI * xi_delta;
                nucl_total_cor += nucl_rho_cor[i] * r * r * r * 4.0 * M_PI * xi_delta;
                fprintf(fp,"%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f", 
                    pp.radius[i], pp.V_local[i], pp.nucl_charge[i], pp.pcc_charge[i], nucl_total,
                    V_local_cor[i], nucl_rho_cor[i], nucl_total_cor);
                for (int k = 0; k < pp.num_radial_projectors; ++k) {
                    fprintf(fp, "\t%f", pp.projector[k*2][i]);
                }
                fprintf(fp, "\n");
            }
            fclose(fp);

            printf("cutoff_vlocal = %f\n", pp.cutoff_vlocal);
            printf("cutoff_vlocal_cor = %f\n", cutoff_vlocal_cor);
            printf("nucl_total = %f\n", nucl_total);
            printf("nucl_total_cor = %f\n", nucl_total_cor);
            printf("ve_total = %f\n", ve_total);
        }
    }
#endif

    //補正を採用//
#ifdef ONCV_CORRECT_VLOCAL
    for (int i = 0; i < num_grids; ++i) {
        pp.V_local[i] = V_local_cor[i];
        pp.nucl_charge[i] = nucl_rho_cor[i];
    }
    pp.cutoff_vlocal = cutoff_vlocal_cor;
#endif


#if 0
    // for test accuracy: pccの精度が悪いのでテスト
    for (int i = 0; i < num_grids; ++i) {
        pp.pcc_charge[i] = -nucl_rho_cor[i];
        //pp.nucl_charge[i] = -pp.pcc_charge[i];
    }
    pp.cutoff_pcc = pp.cutoff_pcc;
    //pp.cutoff_vlocal = pp.cutoff_pcc*4.0;
    //pp.cutoff_pcc = pp.cutoff_vlocal;
//    pp.cutoff_pcc = cutoff_vlocal_cor;
//    pp.cutoff_vlocal = cutoff_vlocal_cor;
#endif

    pp.SortByL();
	return p_pseudo_pot;
			
	
}


inline
int LoadValenceElectronUPF_ONCV(const char* filepath) {

    SimpleXMLPerser xml;
    if (!xml.Open(filepath)) {
        return 0;
    }
    xml.Perse();

    auto a = xml.GetProperty({ "UPF" ,"PP_HEADER" }, "z_valence");
    return std::stol(a);

}
